language: crystal

install:
  - shards install

script:
  - crystal spec
  - crystal bin/ameba.cr
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: docs
  token:
    secure: RBits3tE4sVnVPg758s6TGyjYIRg72HFisA2+zQiRvxhUpURinNVJqXVNkpHvcU4BxeeKMsQ5hUgdpiXzn0nUrWwOOlaHa6BzIIB2EayPmaAY0mEuqnDQOwNJLZ+TWYTsEDT+70VBHWzlEleOQ4PvB3XGapJ+LOz0SpEEghaN3WwEFVKExityrGk+LrPbTmz6rXzapxLsXIjkd9ASuPYoRE7+t5lrQwwNRg3S3GNt2EN74ns7bkZt0WxpWShoGnmV2yk1lvYD/rlXtwlqLRIMmsgzmlxUGMcKTIlgMc3kKoik8xyvK4yoiVizZWBij+eBnN7UEqZmTYNkVDGhihpKNvqQQ4wbqWl9ruJ5zZ0BCEIFyz/fE/DIZkRZXk+8FKvzLETF1lhUSOqL/8mVoR/nqxV7Omyn2aZ7W1qgKaSv0kogvrpuyx7c5pmeflkDGX0kLmVltSNM8seE81EqadjZxiugSPHXheZBCmHRUHcc53rA8oROtmeRtH+A6NEQbdJPirxxQzguS5UcbqoWDUmcnBgrW5bzxxW6wEHR60/rfRhGAwB2hzZfhH42YqG0qX5i3o55nYuO481aL8BXJ9FSlPPLEMzMWIbVOyk/T/mbjak5hzPzrLxS0pkMzPF5fdQLzGKlDfIjjMOlLA77WrPueoEj2lf0Xtfd9N2v35yltU=
